config/routes.rb
WayWeWork::Application.routes.draw do

  get 'posts/:category' =>'posts#by_category', :as => :posts_by_category
  get 'author/:id' =>'posts#by_author', :as => :posts_by_author
  get 'month/:year/:month' =>'posts#by_month', :as => :posts_by_month
  get 'posts/all/:page' =>'posts#index', :as => :all_posts_by_page
  get 'posts/:category/:page' =>'posts#by_category', :as => :posts_by_category_and_page
  get 'author/:id/:page' =>'posts#by_author', :as => :posts_by_author_and_page
  get 'month/:year/:month/:page' =>'posts#by_month', :as => :posts_by_month_and_page
  get '/atom' => 'posts#index', :as => :atom_feed, :format => :atom
  
  resources :feeds

  root :to => 'posts#index'
end

app/models/feed.rb
# == Schema Information
# Schema version: 20081022162832
#
# Table name: feeds
#
#  id         :integer(4)      not null, primary key
#  url        :string(255)
#  name       :string(255)
#  feed_url   :string(255)
#  author     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'rss'
require 'open-uri'

class Feed < ActiveRecord::Base
  has_many :posts, :dependent => :delete_all
  scope :by_most_recent_post, -> { includes(:posts).merge(Post.most_recent_first) }
  scope :by_author, -> { order(:author) }


  after_create { |feed| feed.get_latest unless feed.name && feed.url}
  after_save :follow_on_twitter
  
  def follow_on_twitter
    if Rails.env.production?
      Twitter.follow(twitter_username) if twitter_username_changed? && !twitter_username.empty?
    end
  end
  
  def twitter_username= twitter_username
    twitter_username = twitter_username.sub('@', '') if twitter_username
    super(twitter_username)
  end
  def twitter_username_with_at_sign
    "@#{twitter_username}" unless twitter_username.blank?
  end

  def to_param
    "#{id}-#{author.gsub(' ', '_')}"
  end

  def get_feed
    uri = URI.parse(feed_url)
    uri.read
  end

  def get_posts_from_atom atom_xml
    feed = RSS::Parser.parse(atom_xml, false)
    atom = true
    feed.items.each do |entry|
      atom = !entry.respond_to?(:description)
      if atom && entry.updated
        link = entry.links.detect {|l| l.rel == 'alternate'}
        link = entry.links.first unless link
        link = link.href if link
        published = entry.published ? entry.published.content.to_formatted_s(:db) : nil if entry.respond_to?(:published)

        updated = entry.updated ? entry.updated.content.to_formatted_s(:db) : nil
        published ||= updated

        content = entry.summary || entry.content
        content = content.content if (content.type == 'html' || entry.summary) && content.respond_to?(:content)
        create_post(:contents=>content, :url=>link, :title=>entry.title.content, :category=>category,:published=>published.to_s, :updated=>updated.to_s)
      end
    end unless false
    return false if feed.items.blank?
    return false if !atom
    link = feed.links.detect{|link| link.type=='text/html'}
    link = link.href if link
    update_attributes(:name=>feed.title.content, :url=> link) unless name && url
    return true
  end

  def get_posts_from_rss rss_xml
    rss = RSS::Parser.parse(rss_xml, false)
    rss.items.each { |entry|
      create_post(:contents=>entry.description, :url=>entry.link, :title=>entry.title, :category=>category, :published=>entry.date.to_formatted_s(:db), :updated=>entry.date.to_formatted_s(:db))
    }
    return false if rss.items.blank?
    update_attributes(:name=>rss.channel.title, :url=>rss.channel.link) unless name && url
    return true
  end

  def create_post params
    params.merge!(:feed_id=>id)
    existing_post = Post.find_by_url(params[:url])
    if existing_post
      existing_post.update_attributes(params)
    else
      Post.create(params)
    end
  end


  def get_latest
    puts "getting feed for #{author}-#{name}"
    xml = get_feed
    got_atom_posts = get_posts_from_atom xml
    get_posts_from_rss xml unless got_atom_posts
  end

  def self.update_all
    Feed.all.each do |feed|
      begin
        feed.get_latest
      rescue 
        puts "Error updating feed for #{feed.inspect} #{$!}"
      end
    end
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_filter :authenticate

  # GET /feeds
  # GET /feeds.xml
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.xml
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.xml
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.xml
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        flash[:notice] = 'Feed was successfully created.'
        format.html { redirect_to(@feed) }
        format.xml  { render :xml => @feed, :status => :created, :location => @feed }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.xml
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(feed_params)
        flash[:notice] = 'Feed was successfully updated.'
        format.html { redirect_to(@feed) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feed.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.xml
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to(feeds_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
  def authenticate
    authenticate_or_request_with_http_basic do | user_name, password|
      (user_name == ENV['WAYWEWORK_USERNAME']) && (password == ENV['WAYWEWORK_PASSWORD'])
    end
  end

  private
  def feed_params
    params.require(:feed).permit(:author, :feed_url, :twitter_username, :category)
  end

end

app/views/feeds/edit.html.erb
<div class="content">
<h1>Editing feed</h1>

<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </p>
  <p>
    <%= f.label :twitter_username %><br />
    <%= f.text_field :twitter_username %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select([:agile, :technology, :trivia], :selected=> @feed.category) %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/index.html.erb
<div class="content">

<%= link_to 'New feed', new_feed_path, :class => "btn" %>

<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Twitter Username</th>
    <th>Feed url</th>
    <th>Name</th>
    <th>Url</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for feed in @feeds %>
  <tr>
    <td><%=h feed.author %></td>
    <td><%=h feed.twitter_username_with_at_sign %></td>
    <td><%=h feed.feed_url %></td>
    <td><%=h feed.name %></td>
    <td><%=h feed.url %></td>
    <td><%=h feed.category %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

</div>

app/views/feeds/new.html.erb
<div class="content">
<h1>New feed</h1>

<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </p>
  <p>
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </p>
  <p>
    <%= f.label :twitter_username %><br />
    <%= f.text_field :twitter_username %>
  </p>
  <p>
    <%= f.label :category %><br />
    <%= f.select :category, options_for_select([:agile, :technology, :trivia]) %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', feeds_path %>
</div>

app/views/feeds/show.html.erb
<div class="content">
<p>
  <b>Url:</b>
  <%=h @feed.url %>
</p>

<p>
  <b>Name:</b>
  <%=h @feed.name %>
</p>

<p>
  <b>Author:</b>
  <%=h @feed.author %>
</p>

<p>
  <b>Feed url:</b>
  <%=h @feed.feed_url %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>
</div>