config/routes.rb
WayWeWork::Application.routes.draw do

  get 'posts/:category' =>'posts#by_category', :as => :posts_by_category
  get 'author/:id' =>'posts#by_author', :as => :posts_by_author
  get 'month/:year/:month' =>'posts#by_month', :as => :posts_by_month
  get 'posts/all/:page' =>'posts#index', :as => :all_posts_by_page
  get 'posts/:category/:page' =>'posts#by_category', :as => :posts_by_category_and_page
  get 'author/:id/:page' =>'posts#by_author', :as => :posts_by_author_and_page
  get 'month/:year/:month/:page' =>'posts#by_month', :as => :posts_by_month_and_page
  get '/atom' => 'posts#index', :as => :atom_feed, :format => :atom
  
  resources :feeds

  root :to => 'posts#index'
end

app/models/post.rb
# == Schema Information
# Schema version: 20081022162832
#
# Table name: posts
#
#  id         :integer(4)      not null, primary key
#  feed_id    :integer(4)
#  contents   :text
#  title      :string(255)
#  url        :string(255)
#  published  :date
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  scope :most_recent_first, -> { order('posts.published desc') }
  scope :by_date_published, lambda {|date| where(["published <= ? and published >= ?", date.end_of_month, date.beginning_of_month]) } 

  @styleClass = :blue
  attr_accessor :styleClass

  belongs_to :feed

  after_create :tweet
  delegate :twitter_username, :to => :feed

  def url_with_source
    "#{url}?utm_source=waywework"
  end

  def url_with_source_and_medium(medium)
    "#{url_with_source}&utm_medium=#{medium}"
  end

  def Post.activity_by_date
    activity = Post.group(:published).count(:published) #date_format(published, '%Y-%c')")
    activity_by_date = {}
    activity.each do |row|
      # raise row[0].year.inspect
      year,month = row[0].year, row[0].month #row[0].split '-'
      activity_for_this_year = activity_by_date[year.to_i] ||= {}
      activity_for_this_year[month.to_i] = row[1]
    end
    activity_by_date
  end

  def twitter_username_with_at_sign
    feed.twitter_username_with_at_sign || '@WayWeWorkIT'
  end

  def tweet
    if Rails.env.production?
      if newPost?
        begin
          short_url_length = 20 # should query as this may change.  See https://dev.twitter.com/docs/tco-link-wrapper/faq#Will_t.co-wrapped_links_always_be_the_same_length
          non_title_part_of_tweet = " #{'x'*short_url_length} via #{twitter_username_with_at_sign}"
          max_title_length = 140 - non_title_part_of_tweet.length

          Twitter.update("#{title.truncate(max_title_length)} #{url_with_source_and_medium('twitter')} via #{twitter_username_with_at_sign}")
        rescue
          puts "there was an error sending the tweet"
        end
      end
    end

  end

  def newPost?
    two_days_ago = (Date.today - 2)
    published && published > two_days_ago
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  @@styles = [:red, :orange, :green, :lime, :purple, :yellow, :black, :blue]

  # GET /posts
  def index
    page = get_offset params
    @posts = arrange Post.most_recent_first.offset(page).limit(40).load
    nav_info
    
    respond_to do |format|
      format.html
      format.atom
    end if !params[:page]
    render action: "page", layout: false if params[:page]
  end

  # GET /posts/by_author
  def by_author
    page = get_offset params
    @posts = arrange Post.most_recent_first.offset(page).limit(40).find_all_by_feed_id(params[:id])
    nav_info
    render :action=>:index if !params[:page]
    render action: "page", layout: false if params[:page]
  end

  # GET /posts
  def by_month
    page = get_offset params
    @posts = arrange Post.most_recent_first.offset(page).limit(40).by_date_published(Date.strptime("#{params[:year]}-#{params[:month]}", "%Y-%m"))
    nav_info
    render :action=>:index if !params[:page]
    render action: "page", layout: false if params[:page]
  end

  def by_category
    page = get_offset(params, 60)
    @posts = arrange Post.most_recent_first.offset(page).limit(60).find_all_by_category(params[:category])
    nav_info
    render :action=>:index if !params[:page]
    render action: "page", layout: false if params[:page]
  end

protected
  def nav_info
    @active_feeds = Feed.by_most_recent_post
    @activity_by_date = Post.activity_by_date
  end

  def get_offset(params, entries_per_page = 40)
    page = params[:page]
    page ||= 1
    (page.to_i-1)*entries_per_page
  end

  def arrange(posts)
    rows = []
    row = []
    post_index = 0
    posts.each do |post|
      row = [] if (post_index % 4 == 0)
      rows << row if (post_index % 4 == 0)
      post.styleClass = @@styles[post_index % 4] if rows.length % 2 == 1
      post.styleClass = @@styles[4 + (post_index % 4)] if rows.length % 2 == 0
      row << post
      post_index += 1
    end

    rows
  end
end

app/views/posts/_archive.html.erb
<h2><a onclick="toggle('archives')">Archive</h2>
<ul id="archives">
<% @activity_by_date.keys.sort.reverse.each do |year| %>
  <li><%= year %></li>
  <ul>
    <% @activity_by_date[year].keys.sort.reverse.each do |month| %>
    <li><%= link_to(Date::MONTHNAMES[month], posts_by_month_url(year, month))%></li>
    <% end %>
  </ul>
  <% end %>
</ul>

app/views/posts/_posts.html.erb
<% @posts.each do |row| %>

<div class="row">
  <% row.each do |post| %>
  <div class="col <%=post.styleClass%>">
    <div class="container-<%=post.styleClass%>">
      <div class="post-container">
        <h1><%= link_to post.title, post.url_with_source_and_medium('referral') %></h1>
        <h2><%= distance_of_time_in_words(Time.now, post.published) %> ago | <%= link_to "#{post.feed.author}: #{post.feed.name}", post.feed.url %></h2>

        <p class="content"><%= sanitize post.contents.html_safe, :tags => %w(img a) %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<% end %>
<div class="next-page"><!-- this is where the next lot will be injected --></div>

app/views/posts/_whos_talking.html.erb
<h2><a onclick="toggle('authors')">Who is talking?</a></h2>
<ul id="authors">
<% @active_feeds.each { |feed| %><li><%=link_to(feed.author, posts_by_author_url(feed))%></li><%}%>
</ul>

app/views/posts/index.html.erb
<div id="site">

  <div class="right right_column">
    <%= render :partial=>'posts/whos_talking'%>
    <%= render :partial=>'posts/archive'%>

  </div>

  <div class="left left_column">

    <div class="blogs">
      <nav>
        <ul>
          <li><%= link_to "All", root_url, :class=>"nav_item_all" %> </li>
          <li><%= link_to "Agile", posts_by_category_url(:agile), :class=>"nav_item_agile" %></li>
          <li><%= link_to "Technology", posts_by_category_url(:technology), :class=>"nav_item_tech" %></li>
          <li><%= link_to "Trivia", posts_by_category_url(:trivia), :class=>"nav_item_trivia" %></li>
        </ul>
      </nav>

      <%= render 'posts/posts'%>
      <div class="row">
        <a class="nextPage" onclick="javascript:nextPage();">More</a>
      </div>
    </div>

  </div>

  <div class="clear"></div>
</div>

<script type="text/javascript">

var page = 1;
var endOfDoc = false;
 
$(window).scroll(function(){
  if(!endOfDoc){
    if ($(window).scrollTop() >= $(document).height() - $(window).height()) {
      nextPage();
     };
  };
});

function nextPage() {
  endOfDoc = true;
  page++;
  var path = document.location.href;

  if (document.location.pathname === "/") path = document.location.href + "posts/all";
  
  $(".next-page").last().append().load(path + '/' + page,function(event){
    endOfDoc = false;
    //event.preventDefault();
    return false;
  });
}

</script>

app/views/posts/page.html.erb
<%= render 'posts/posts'%>