config/routes.rb
WayWeWork::Application.routes.draw do

  get 'posts/:category' =>'posts#by_category', :as => :posts_by_category
  get 'author/:id' =>'posts#by_author', :as => :posts_by_author
  get 'month/:year/:month' =>'posts#by_month', :as => :posts_by_month
  get 'posts/all/:page' =>'posts#index', :as => :all_posts_by_page
  get 'posts/:category/:page' =>'posts#by_category', :as => :posts_by_category_and_page
  get 'author/:id/:page' =>'posts#by_author', :as => :posts_by_author_and_page
  get 'month/:year/:month/:page' =>'posts#by_month', :as => :posts_by_month_and_page
  get '/atom' => 'posts#index', :as => :atom_feed, :format => :atom
  
  resources :feeds

  root :to => 'posts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content="java, .net, c#, ruby, rails, nodejs, javascript, angularjs, agile, scrum">
  <meta name="description" content="blog feed aggregator of various technology sites">

  <title>Way We Work</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="alternate" type="application/atom+xml" title="WayWeWork - Atom" href="<%= atom_feed_url %>" />
  <%= csrf_meta_tags %>

  <!--[if lt IE 7.]>
    <script defer type="text/javascript" src="/javascripts/pngfix.js"></script>
  <![endif]-->
</head>
<body>

  <!-- div id="band"></div -->
  <div id="wrapper">
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </div>

</body>
</html>